plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

RSpec/ExampleLength:
  Max: 100

RSpec/MultipleExpectations:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive
